name: Update Repositories

on:
  push:
    branches: [main]

jobs:
  update-repositories:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitOps-dev repository
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-dev
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: /GitOps-dev

    - name: Checkout GitOps-prod repository
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-prod
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: /GitOps-prod


    - name: Commit changes to GitOps-prod
      run: |
        git config user.email "ariyonzor@gmail.com"
        git config user.name "ArielDomchik"
        cp -r ./GitOps-dev/templates ./GitOps-prod/
        cp -r ./GitOps-dev/Chart.yaml ./GitOps-prod/
        rm ./Personal-space/values.yaml
        cp -r ./GitOps-dev/values.yaml ./Personal-space/
        git add .
        git commit -m "Update GitOps-prod and Personal-space with latest changes"
        git push origin main
