name: Update Repositories

on:
  push:
    branches: [main]

jobs:
  update-repositories:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Personal-space repository
      uses: actions/checkout@v2
      with:
           repository: ArielDomchik/Personal-space
           ref: main
           token: ${{ secrets.API_TOKEN_GITHUB }}
           path: /home/runner/work/GitOps-dev/GitOps-dev/Personal-space

    - name: Checkout GitOps-prod repository
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-prod
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: /home/runner/work/GitOps-dev/GitOps-dev/GitOps-prod
           
    - name: Checkout GitOps-dev repository
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-dev
        ref: main
        token: ${{ secrets.API_TOKEN_GITHUB }}
        path: /home/runner/work/GitOps-dev/GitOps-dev/GitOps-dev

    - name: Commit changes to GitOps-prod
      run: |
        ls
        pwd
        cd GitOps-dev
        ls
        pwd
        git config user.email "ariyonzor@gmail.com"
        git config user.name "ArielDomchik"
        cp -r /home/runner/work/GitOps-dev/GitOps-dev/GitOps-dev/templates /home/runner/work/GitOps-dev/GitOps-dev/GitOps-prod
        cp -r /home/runner/work/GitOps-dev/GitOps-dev/GitOps-dev/Chart.yaml /home/runner/work/GitOps-dev/GitOps-dev/GitOps-prod
        cd ../GitOps-prod
        git config user.email "ariyonzor@gmail.com"
        git config user.name "ArielDomchik"
        git add .
        git commit -m "Update GitOps-prod with latest changes"
        git push origin main
        rm /home/runner/work/GitOps-dev/GitOps-dev/Personal-space/values.yaml
        cp -r /home/runner/work/GitOps-dev/GitOps-dev/GitOps-dev/values.yaml /home/runner/work/GitOps-dev/GitOps-dev/Personal-space
        cd ../Personal-space
        git config user.email "ariyonzor@gmail.com"
        git config user.name "ArielDomchik"
        git add .
        git commit -m "Update GitOps-prod and Personal-space with latest changes"
        git push origin main
