name: Replace dev with prod

on:
  push:
    branches:
      - main

jobs:
  replace:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@v2
        with:
          repository: username/GitOps-dev
          token: ${{ secrets.API_TOKEN_GITHUB }}
      
      - name: Checkout prod
        uses: actions/checkout@v2
        with:
          repository: username/GitOps-prod
          token: ${{ secrets.API_TOKEN_GITHUB }}
          
      - name: Checkout Personal-space
        uses: actions/checkout@v2
        with:
          repository: username/Personal-space
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Replace dev with prod
        run: |
          rsync -r --exclude='values.yml' --exclude='README.md' ./GitOps-dev/ ./GitOps-prod/
          cp ./GitOps-dev/values.yml ./Personal-space/values.yml
        working-directory: ./repositories
        
      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          cd ./GitOps-prod/
          git add .
          git commit -m "Replace dev with prod"
          git push
          
          cd ../Personal-space/
          git add values.yml
          git commit -m "Update values.yml from GitOps-dev"
          git push
        working-directory: ./repositories
