name: Update Repositories

on:
  push:
    branches: [ main ]

jobs:
  update_repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitOps-prod Repository
        uses: actions/checkout@v2
        with:
          repository: ArielDomchik/GitOps-prod
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Clone GitOps-dev Repository
        uses: actions/checkout@v2
        with:
          repository: ArielDomchik/GitOps-dev
          ref: main
          token: ${{ secrets.API_TOKEN_GITHUB

      - name: Copy Contents from GitOps-dev to GitOps-prod
        run: |
          rsync -r --exclude='values.yaml' --exclude='README.md' GitOps-dev/ GitOps-prod/

      - name: Clone Personal-space Repository
        uses: actions/checkout@v2
        with:
          repository: ArielDomchik/Personal-space
          ref: main
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Copy values.yaml from GitOps-dev to Personal-space
        run: |
          cp GitOps-dev/values.yaml Personal-space/values.yaml

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: Update repositories with latest changes
          add: .
          push: true
          token: ${{ secrets.API_TOKEN_GITHUB }}
