name: Copy Dev to Prod

on:
  push:
    branches:
      - main # change this to your main branch name

jobs:
  copy:
    runs-on: ubuntu-latest
    steps:
      - name: Push to Prod Repository
        uses: cpina/github-action-push-to-another-repository@main
        with:
          source-directory: dev-code/output
          destination-github-username: ArielDomchik # replace with your prod repository information
          destination-repository-name: GitOps-prod # replace with your prod repository information
          user-email: ariyonzor@gmail.com # replace with your email address
          target-branch: main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
