name: Update Repositories

on:
  push:
    branches: [main]

jobs:
  update-repos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitOps-dev
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-dev
    - name: Checkout GitOps-prod
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-prod
    - name: Checkout Personal-space
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/Personal-space
    - name: Copy files from GitOps-dev to GitOps-prod
      run: |
        rsync -r --exclude='values.yaml' --exclude='README.md' GitOps-dev/ GitOps-prod/
      working-directory: ./GitOps-dev
    - name: Copy values.yaml from GitOps-dev to Personal-space
      run: |
        cp GitOps-dev/values.yaml Personal-space/
      working-directory: ./
    - name: Commit changes and push to GitOps-prod and Personal-space
      run: |
        git config --local user.email "ariyonzor@gmail.com"
        git config --local user.name "ArielDomchik"
        git add -A
        git commit -m "Update repositories"
        git push
      working-directory: ./GitOps-prod
