name: Update Repositories

on:
  push:
    branches:
      - main

jobs:
  update_repositories:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitOps-dev
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-dev
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: Checkout GitOps-prod
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/GitOps-prod
        token: ${{ secrets.API_TOKEN_GITHUB }}
    - name: Checkout Personal-space
      uses: actions/checkout@v2
      with:
        repository: ArielDomchik/Personal-space
        token: ${{ secrets.API_TOKEN_GITHUB }}    
        ref: main
    - name: Update GitOps-prod
      run: |
        rsync -r --exclude='values.yaml' --exclude='README.md' ./GitOps-dev/ ./GitOps-prod/
    - name: Update Personal-space
      run: |
        cp ./GitOps-dev/values.yaml ./Personal-space/values.yaml
    - name: Commit Changes
      run: |
        git config --global user.email "ariyonzor@gmail.com"
        git config --global user.name "ArielDomchik"
        git add .
        git commit -m "Update repositories"
        git push
